server:
  port: 8019
  servlet:
    encoding:
      charset: UTF-8

spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL

person:
  name: zhen.yin
  age: 18
  addr:
    - 北京
    - 郑州
  maps: {key1: "v1",key2: "v2"}




logging.config: classpath:logback-spring.xml
   